[lint]
select = ["E", "F", "B", "W", "C90", "I", "N", "D", "UP", "YTT", "ANN", "ASYNC", "S", "BLE", "FBT", "B", "A", "COM", "C4", "DTZ", "DJ", "EM", "ISC", "ICN", "INP", "PIE", "PYI", "Q", "RSE", "RET", "SLF", "SIM", "TID", "TCH", "INT", "ARG", "PTH", "TD", "FIX", "PD", "PL", "FLY", "NPY", "PERF", "FURB", "DOC", "RUF"]

