# Generated by Django 5.2 on 2025-04-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_units',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
