# Generated by Django 5.2 on 2025-04-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0002_alter_product_current_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
