# Generated by Django 5.2 on 2025-04-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0004_alter_invoice_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='gross_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ship_to',
            field=models.TextField(blank=True),
        ),
    ]
