# Generated by Django 5.2 on 2025-04-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0005_remove_invoice_gross_total_remove_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partially Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
    ]
