# Generated by Django 5.2 on 2025-04-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0007_alter_invoice_gross_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
