# Generated by Django 5.2 on 2025-04-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0008_alter_invoice_discount_alter_invoice_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceserviceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
