# Generated by Django 5.2 on 2025-04-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0009_alter_invoiceserviceitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
