# Generated by Django 5.2 on 2025-04-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0013_alter_expense_date_alter_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='payment_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
